[project]
name = "ai-storyteller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "colombefioren", email = "colomberakotonjanahary@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ai-storyteller = "ai_storyteller:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
